<template>
  <q-page class="q-pa-lg">
    <h5>Help</h5>
    <p>Est aute cillum deserunt laboris laborum consectetur culpa reprehenderit elit. Consequat dolor deserunt culpa veniam sunt velit sint aute duis commodo magna elit Lorem proident. In sint sit tempor consectetur aliquip. Nisi sit esse non ut Lorem deserunt pariatur. Aute laboris consequat aliqua et consectetur ipsum excepteur occaecat irure in nulla excepteur. Velit tempor et dolore anim eu excepteur deserunt veniam occaecat incididunt. Nulla incididunt anim veniam ipsum minim occaecat in ullamco ad id id non.</p>
  </q-page>
</template>
  
<script>
  import { defineComponent } from 'vue';
  
  export default defineComponent({
    name: 'HelpPage'
  })
</script>
